# Generated by Django 4.2 on 2023-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gitl_commitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_ID', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('authored_date', models.CharField(max_length=200)),
                ('responsible_person', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('make_sure', models.BooleanField(default=False)),
            ],
        ),
    ]
